# This file is machine-generated - editing it directly is not advised

julia_version = "1.7.2"
manifest_format = "2.0"

[[deps.ArgTools]]
uuid = "0dad84c5-d112-42e6-8d28-ef12dabb789f"

[[deps.Artifacts]]
uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[[deps.Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[deps.Crayons]]
git-tree-sha1 = "249fe38abf76d48563e2f4556bebd215aa317e15"
uuid = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
version = "4.1.1"

[[deps.Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[deps.Downloads]]
deps = ["ArgTools", "LibCURL", "NetworkOptions"]
uuid = "f43a241f-c20a-4ad4-852c-f6b1247861c6"

[[deps.HTTP]]
deps = ["Base64", "Dates", "IniFile", "Logging", "MbedTLS", "NetworkOptions", "Sockets", "URIs"]
git-tree-sha1 = "0fa77022fe4b511826b39c894c90daf5fce3334a"
uuid = "cd3eb016-35fb-5094-929b-558a96fad6f3"
version = "0.9.17"

[[deps.IniFile]]
git-tree-sha1 = "f550e6e32074c939295eb5ea6de31849ac2c9625"
uuid = "83e8ac13-25f8-5344-8a64-a9f2b223428f"
version = "0.5.1"

[[deps.InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[deps.LibCURL]]
deps = ["LibCURL_jll", "MozillaCACerts_jll"]
uuid = "b27032c2-a3e7-50c8-80cd-2d36dbcbfd21"

[[deps.LibCURL_jll]]
deps = ["Artifacts", "LibSSH2_jll", "Libdl", "MbedTLS_jll", "Zlib_jll", "nghttp2_jll"]
uuid = "deac9b47-8bc7-5906-a0fe-35ac56dc84c0"

[[deps.LibGit2]]
deps = ["Base64", "NetworkOptions", "Printf", "SHA"]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[deps.LibSSH2_jll]]
deps = ["Artifacts", "Libdl", "MbedTLS_jll"]
uuid = "29816b5a-b9ab-546f-933c-edad1886dfa8"

[[deps.Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[deps.Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[deps.Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[deps.MbedTLS]]
deps = ["Dates", "MbedTLS_jll", "MozillaCACerts_jll", "Random", "Sockets"]
git-tree-sha1 = "14cb991ee7ccc6dabda93d310400575c3cae435b"
uuid = "739be429-bea8-5141-9913-cc70e7f3736d"
version = "1.1.2"

[[deps.MbedTLS_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "c8ffd9c3-330d-5841-b78e-0817d7145fa1"

[[deps.MozillaCACerts_jll]]
uuid = "14a3606d-f60d-562e-9121-12d972cd8159"

[[deps.NetworkOptions]]
uuid = "ca575930-c2e3-43a9-ace4-1e988b2c1908"

[[deps.ParseNotEval]]
deps = ["Dates"]
git-tree-sha1 = "f583ed64aa1f38d85909109503a150f63d52d592"
uuid = "8aa82b3d-5f10-4499-b4c6-079a0c256bc8"
version = "0.1.0"

[[deps.Pkg]]
deps = ["Artifacts", "Dates", "Downloads", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "REPL", "Random", "SHA", "Serialization", "TOML", "Tar", "UUIDs", "p7zip_jll"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[deps.REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets", "Unicode"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[deps.Random]]
deps = ["SHA", "Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[deps.ReplMaker]]
deps = ["REPL", "Unicode"]
git-tree-sha1 = "f8bb680b97ee232c4c6591e213adc9c1e4ba0349"
uuid = "b873ce64-0db9-51f5-a568-4457d8e49576"
version = "0.2.7"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[deps.Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[deps.Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[deps.TOML]]
deps = ["Dates"]
uuid = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[[deps.Tar]]
deps = ["ArgTools", "SHA"]
uuid = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"

[[deps.Toolips]]
deps = ["Crayons", "Dates", "HTTP", "ParseNotEval", "Pkg", "Sockets"]
git-tree-sha1 = "827aa7260f159d84754e0680954ec9cba9608a1f"
repo-rev = "Unstable"
repo-url = "https://github.com/ChifiSource/Toolips.jl.git"
uuid = "a47e2ad8-fcf7-417c-9746-32b9bdf220bd"
version = "0.2.1"

[[deps.ToolipsBase64]]
deps = ["Base64", "Toolips", "ToolipsSession"]
git-tree-sha1 = "e43969303ee12dfbd9dda22027caab9bef844681"
repo-rev = "main"
repo-url = "https://github.com/ChifiSource/ToolipsBase64.jl"
uuid = "35c70e29-c044-44e8-ae14-cceff0bd3f12"
version = "0.1.1"

[[deps.ToolipsDefaults]]
deps = ["Toolips", "ToolipsSession"]
git-tree-sha1 = "b73a06a3e9626b5bdd8fec518df320afb04f19dc"
repo-rev = "main"
repo-url = "https://github.com/ChifiSource/ToolipsDefaults.jl"
uuid = "1710be6b-e895-498d-ba35-e3ff0dac7995"
version = "0.1.0"

[[deps.ToolipsMarkdown]]
deps = ["Markdown", "Toolips"]
git-tree-sha1 = "9248ccc0d0114e73a0169b2687a6d27199fb722d"
repo-rev = "main"
repo-url = "https://github.com/ChifiSource/ToolipsMarkdown.jl"
uuid = "33f7ff50-f2f2-41f0-8a96-482dce5c1514"
version = "0.1.1"

[[deps.ToolipsMemWrite]]
deps = ["Toolips"]
git-tree-sha1 = "241e8c570cccf3029e69e9ebf3d37830775123dc"
repo-rev = "main"
repo-url = "https://github.com/ChifiSource/ToolipsMemWrite.jl"
uuid = "57c31d6b-7ec9-45e4-80ae-c449616bb020"
version = "0.1.0"

[[deps.ToolipsRemote]]
deps = ["Markdown", "ParseNotEval", "Random", "ReplMaker", "Toolips"]
git-tree-sha1 = "3e45bb9ba9248e289c16f408d0df49f50637a61b"
repo-rev = "main"
repo-url = "https://github.com/ChifiSource/ToolipsRemote.jl"
uuid = "706d13b3-298e-4297-9e9a-14f4a49b71e5"
version = "0.1.0"

[[deps.ToolipsSession]]
deps = ["Dates", "ParseNotEval", "Random", "Toolips"]
git-tree-sha1 = "55ea7a4060bcb253363e56f3c75bc13ef78adf54"
repo-rev = "Unstable"
repo-url = "https://github.com/ChifiSource/ToolipsSession.jl"
uuid = "2fe55384-55bc-4df3-9d59-c817d405cd05"
version = "0.2.0"

[[deps.ToolipsUploader]]
deps = ["Toolips", "ToolipsSession"]
git-tree-sha1 = "f765e96365a0b460100a50348e7b2f6b6dd6c142"
repo-rev = "main"
repo-url = "https://github.com/ChifiSource/ToolipsUploader.jl"
uuid = "8d58c116-97a2-4dce-9816-d8d464dcb6e5"
version = "0.1.0"

[[deps.URIs]]
git-tree-sha1 = "e59ecc5a41b000fa94423a578d29290c7266fc10"
uuid = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
version = "1.4.0"

[[deps.UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[deps.Zlib_jll]]
deps = ["Libdl"]
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"

[[deps.nghttp2_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "8e850ede-7688-5339-a07c-302acd2aaf8d"

[[deps.p7zip_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "3f19e933-33d8-53b3-aaab-bd5110c3b7a0"
